# TABLE 2
Code to generate table 2

## Reqs

To run this notebook you have to download / get following files in addition to the files already present in the repository :
- `data/clinvar/clinvar_mutation_context.csv` available from Zenodo
- `data/cosmic/cosmic_mutation_context.csv` has to be generated following mat & met
- `data/somamutdb/somamutdb_mutation_context.csv` has to be generated following mat & met
- `hg38/kmer_counts_3N.csv` available from github and Zenodo
- `hg38/kmer_counts_5N.csv` available from github and Zenodo

In [2]:
GENERATE_RESULTS = True

import polars as pl
from scipy import stats
import matplotlib
from pathlib import Path
from viper import Viper
from utils import load_data, utils
from utils.utils import get_table_of_corr, print_markdown

fontdict = {"size": 14, "family": "sans-serif"}
matplotlib.rc("font", **fontdict)

PROJECT_DIR = Path().absolute().parent
VIPER = Viper()

In [3]:
datas = pl.concat(
    [
        pl.read_csv(
            PROJECT_DIR / "data" / db / f"{db}_mutation_context.csv",
            separator=",",
            schema_overrides={"chromosome": pl.Utf8},
        ).with_columns(
            pl.col("context").str.slice(4, 3).alias("3N"),
            pl.col("context").str.slice(3, 5).alias("5N"),
            pl.lit(db).alias("db"),
        )
        for db in ["cosmic", "clinvar", "somamutdb"]
    ],
    how="diagonal_relaxed",
).filter(~pl.col("context").str.contains("N"), pl.col('alt').str.len_chars()==1)

In [4]:
kmer3 = load_data.get_kmer_df(PROJECT_DIR / "hg38", 3)["context", "frequencies"]
kmer5 = load_data.get_kmer_df(PROJECT_DIR / "hg38", 5)["context", "frequencies"]

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

TYPE_ORDER = [
    "silent",
    "missense",
    "nonsense",
    "intronic",
    "UTR",
    "splice_region",
    "intergenic",
]
DB_ORDER = ["cosmic", "somamutdb", "clinvar", "all"]


def run_table2(
    df, kmer, context_col, category_col="type", categories=TYPE_ORDER, db_order=DB_ORDER, stat_method = stats.pearsonr, prefix = None
):
    df_with_all = pl.concat(
        [df, df.with_columns(pl.lit("all").alias("db"))],
        how="diagonal_relaxed",
    )
    aggregated = utils.aggregate_data(
        df_with_all.group_by([category_col, context_col, "db"]).len(),
        kmer,
        on=[category_col, "db", "context"],
        over=[category_col, "db"],
        context_col=context_col,
    )
    table_of_corr = get_table_of_corr(
            aggregated,
            categories=("db", db_order),
            sub_categories=(category_col, categories),
            corr_method=stat_method,
        )
    print_markdown(
        table_of_corr
    )
    if GENERATE_RESULTS and prefix:
        output_path = PROJECT_DIR / "outputs" / "datasets"  /  f"{prefix}_{stat_method.__name__}.tsv"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        table_of_corr.write_csv(output_path, separator="\t")
    return aggregated

def compute_partial_corr_table(aggregated, db_order=DB_ORDER, type_order=TYPE_ORDER, stat_method=stats.pearsonr, prefix=None):
    """Partial correlation between F and vip controlling for GC content of context."""
    agg_gc = aggregated.with_columns(
        pl.col("context")
        .map_elements(
            lambda ctx: sum(1 for c in ctx if c in "GC"), return_dtype=pl.Int32
        )
        .alias("gc_count")
    )
    rows = []
    for db in db_order:
        for t in type_order:
            subset = agg_gc.filter((pl.col("db") == db) & (pl.col("type") == t))
            if len(subset) < 4:
                continue
            r, p = utils.partial_correlation(
                subset, "F", "vip", "gc_count", stat_method=stat_method
            )
            rows.append({"db": db, "type": t, "partial_r": r, "p_value": p})

    sort_key = {t: i for i, t in enumerate(type_order)}

    result = (
        pl.DataFrame(rows)
        .pivot(values="partial_r", index="type", on="db", aggregate_function=None)
        .with_columns(pl.col("type").replace_strict(sort_key).alias("_sort"))
        .sort("_sort")
        .drop("_sort")
        .select(["type"] + [db for db in db_order if db in pl.DataFrame(rows)["db"].unique()])
    )
    print(type_order)
    if len(type_order) ==1 and len(db_order)== 1:
        return result
    if GENERATE_RESULTS and prefix:
        output_path = PROJECT_DIR / "outputs" / "datasets" / f"{prefix}_corrected_{stat_method.__name__}.tsv"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        result.write_csv(output_path, separator="\t")

    return result

import math
from itertools import product

def get_pyrimidine_strand(seq):
    mapper = {"A": "T", "C": "G", "G": "C", "T": "A"}
    if seq[math.floor(len(seq) / 2)] in ["T", "C"]:
        return seq
    new_seq = ""
    for nucl in seq[::-1]:
        new_seq += mapper.get(nucl)
    return new_seq

def rev_comp(seq):
    mapper = {"A": "T", "C": "G", "G": "C", "T": "A"}
    return "".join(mapper[b] for b in seq[::-1])

STOP_CODONS = {"TAA", "TAG", "TGA"}
BASES = ["A", "T", "C", "G"]

def get_codons_3mer(kmer):
    X, Y, Z = kmer[0], kmer[1], kmer[2]
    codons = []
    for mut in [b for b in BASES if b != Y]:
        for N in BASES:
            codons.append(N + X + mut)
        codons.append(X + mut + Z)
        for N in BASES:
            codons.append(mut + Z + N)
    return codons

def get_codons_5mer(kmer):
    p = list(kmer)
    codons = []
    for mut in [b for b in BASES if b != p[2]]:
        codons.append(p[0] + p[1] + mut)
        codons.append(p[1] + mut + p[3])
        codons.append(mut + p[3] + p[4])
    return codons

def can_produce_stop(codons):
    for codon in codons:
        if codon in STOP_CODONS or rev_comp(codon) in STOP_CODONS:
            return True
    return False

def get_all_kmers(size, canonical=False):
    all_kmer = ["".join(p) for p in product(BASES, repeat=size)]
    if canonical:
        return sorted(set(get_pyrimidine_strand(k) for k in all_kmer))
    else :
        return sorted(set(all_kmer))

canonical_3 = get_all_kmers(size=3, canonical=True)
canonical_5 = get_all_kmers(size=5, canonical=True)


poss_3 = [k for k in canonical_3 if can_produce_stop(get_codons_3mer(k))]
impo_3 = [k for k in canonical_3 if not can_produce_stop(get_codons_3mer(k))]
poss_5 = [k for k in canonical_5 if can_produce_stop(get_codons_5mer(k))]
impo_5 = [k for k in canonical_5 if not can_produce_stop(get_codons_5mer(k))]

SyntaxError: expected ':' (1214009505.py, line 77)

In [6]:
# --- Trinucleotide context (3N) ---
stat_methods = [stats.pearsonr, stats.spearmanr]
for stat_method in stat_methods:
    print(f"### {stat_method.__name__} correlation (3N): F ~ vip")
    agg3 = run_table2(datas, kmer3, "3N", prefix="3N", stat_method=stat_method)
    print("### Partial correlation (3N): F ~ vip | GC content")
    result = compute_partial_corr_table(agg3, prefix="3N", stat_method=stat_method)
    print_markdown(result)

### pearsonr correlation (3N): F ~ vip
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.85 |       -0.87 |     -0.86 | -0.86 |
| missense      |    -0.77 |       -0.76 |     -0.72 | -0.76 |
| nonsense      |    -0.7  |       -0.62 |     -0.61 | -0.69 |
| intronic      |    -0.67 |       -0.71 |     -0.74 | -0.69 |
| UTR           |    -0.75 |       -0.75 |     -0.75 | -0.76 |
| splice_region |    -0.61 |       -0.68 |     -0.64 | -0.64 |
| intergenic    |    -0.72 |       -0.72 |     -0.8  | -0.72 |
### Partial correlation (3N): F ~ vip | GC content
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.7  |       -0.74 |     -0.72 | -0.72 |
| missense      |    -0.52 |       -0.52 |     -0.45 | -0.52 |
| nonsense      |    -0.55 |       -0.5  |     -0.45 | -0.54 |
| intronic      |    -0.53 |       -0.57 |     -0.53 | -0.54 |
| UTR           |    -0.58 |       -0.59 |     -0.56 | -0.59 |
| splice_region |    -0.41 |       -0.49 |     -0.41 | -0.43 |
| intergenic    |    -0.55 |       -0.57 |     -0.56 | -0.57 |
### spearmanr correlation (3N): F ~ vip
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.82 |       -0.85 |     -0.88 | -0.84 |
| missense      |    -0.72 |       -0.73 |     -0.63 | -0.72 |
| nonsense      |    -0.66 |       -0.56 |     -0.56 | -0.67 |
| intronic      |    -0.57 |       -0.64 |     -0.66 | -0.6  |
| UTR           |    -0.68 |       -0.66 |     -0.69 | -0.67 |
| splice_region |    -0.53 |       -0.56 |     -0.52 | -0.56 |
| intergenic    |    -0.64 |       -0.63 |     -0.74 | -0.64 |
### Partial correlation (3N): F ~ vip | GC content
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.66 |       -0.73 |     -0.8  | -0.7  |
| missense      |    -0.45 |       -0.44 |     -0.22 | -0.45 |
| nonsense      |    -0.49 |       -0.44 |     -0.4  | -0.51 |
| intronic      |    -0.41 |       -0.46 |     -0.42 | -0.43 |
| UTR           |    -0.45 |       -0.48 |     -0.41 | -0.44 |
| splice_region |    -0.33 |       -0.36 |     -0.29 | -0.34 |
| intergenic    |    -0.41 |       -0.46 |     -0.48 | -0.47 |

In [7]:
compute_partial_corr_table(agg3, prefix="3N", stat_method=stat_method)

shape: (7, 5)
┌───────────────┬───────────┬───────────┬───────────┬───────────┐
│ type          ┆ cosmic    ┆ somamutdb ┆ clinvar   ┆ all       │
│ ---           ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str           ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ silent        ┆ -0.662128 ┆ -0.725354 ┆ -0.795653 ┆ -0.704569 │
│ missense      ┆ -0.450427 ┆ -0.441162 ┆ -0.224716 ┆ -0.45349  │
│ nonsense      ┆ -0.494136 ┆ -0.436045 ┆ -0.396328 ┆ -0.509335 │
│ intronic      ┆ -0.406504 ┆ -0.460397 ┆ -0.420249 ┆ -0.429301 │
│ UTR           ┆ -0.448984 ┆ -0.475089 ┆ -0.414481 ┆ -0.44139  │
│ splice_region ┆ -0.333282 ┆ -0.360266 ┆ -0.286942 ┆ -0.344958 │
│ intergenic    ┆ -0.414938 ┆ -0.459163 ┆ -0.480167 ┆ -0.470359 │
└───────────────┴───────────┴───────────┴───────────┴───────────┘

In [8]:
# --- Pentanucleotide context (5N) ---

# Filter keeping only k-mers that can produce a stop codon via a central SNP,
# applied exclusively to nonsense variants. Two biological justifications:
#
# 1. A "possible" k-mer guarantees that the immediate sequence context
#    allows the formation of a stop codon (TAA/TAG/TGA) on either strand,
#    in at least one of the 3 possible reading frames — accounting for both
#    forward and reverse strand orientations via pyrimidine strand normalization.
#
# 2. A k-mer may span an exon-intron junction. After splicing, flanking exons
#    are reconstituted into a new sequence context that differs from the genomic
#    one (e.g. GCCGG on the reverse strand of PIGQ -> C|CGA|G -> C|UGA|G = Stop),
#    making the genomic k-mer non-representative of the actual translated codon.
#    These cases are retained by default (filter not applied for non-nonsense types)
filtered_df = (
    datas
    .with_columns(
            pl.col('5N')
    .map_elements(utils.get_pyrimidine_strand, return_dtype=pl.String)
    .alias('5N_canonical')
    )
    .filter(
        pl.when(pl.col("type") == "nonsense")
        .then(pl.col("5N_canonical").is_in(poss_5))
        .otherwise(pl.lit(True))
    )
)
filtered_df

stat_methods = [stats.pearsonr, stats.spearmanr]
for stat_method in stat_methods:
    print(f"### {stat_method.__name__} correlation (5N): F ~ vip")
    agg5 = run_table2(filtered_df, kmer5, "5N", prefix="5N", stat_method=stat_method)
    print("### Partial correlation (5N): F ~ vip | GC content")
print_markdown(compute_partial_corr_table(agg5, prefix="5N", stat_method=stat_method))

### pearsonr correlation (5N): F ~ vip
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.77 |       -0.79 |     -0.77 | -0.78 |
| missense      |    -0.73 |       -0.76 |     -0.71 | -0.73 |
| nonsense      |    -0.63 |       -0.59 |     -0.6  | -0.59 |
| intronic      |    -0.59 |       -0.64 |     -0.69 | -0.62 |
| UTR           |    -0.7  |       -0.7  |     -0.75 | -0.71 |
| splice_region |    -0.47 |       -0.52 |     -0.45 | -0.47 |
| intergenic    |    -0.66 |       -0.61 |     -0.78 | -0.63 |
### Partial correlation (5N): F ~ vip | GC content
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.58 |       -0.61 |     -0.57 | -0.59 |
| missense      |    -0.49 |       -0.53 |     -0.45 | -0.49 |
| nonsense      |    -0.47 |       -0.47 |     -0.44 | -0.43 |
| intronic      |    -0.51 |       -0.57 |     -0.51 | -0.53 |
| UTR           |    -0.53 |       -0.57 |     -0.56 | -0.55 |
| splice_region |    -0.28 |       -0.37 |     -0.24 | -0.28 |
| intergenic    |    -0.53 |       -0.56 |     -0.53 | -0.57 |
### spearmanr correlation (5N): F ~ vip
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.74 |       -0.78 |     -0.75 | -0.76 |
| missense      |    -0.68 |       -0.71 |     -0.65 | -0.69 |
| nonsense      |    -0.65 |       -0.58 |     -0.61 | -0.64 |
| intronic      |    -0.43 |       -0.52 |     -0.62 | -0.48 |
| UTR           |    -0.62 |       -0.61 |     -0.69 | -0.64 |
| splice_region |    -0.41 |       -0.47 |     -0.37 | -0.4  |
| intergenic    |    -0.56 |       -0.49 |     -0.75 | -0.5  |
### Partial correlation (5N): F ~ vip | GC content
| type          |   cosmic |   somamutdb |   clinvar |   all |
|---------------|----------|-------------|-----------|-------|
| silent        |    -0.51 |       -0.58 |     -0.5  | -0.52 |
| missense      |    -0.37 |       -0.42 |     -0.29 | -0.37 |
| nonsense      |    -0.47 |       -0.45 |     -0.43 | -0.46 |
| intronic      |    -0.32 |       -0.43 |     -0.38 | -0.37 |
| UTR           |    -0.39 |       -0.44 |     -0.42 | -0.41 |
| splice_region |    -0.2  |       -0.3  |     -0.14 | -0.18 |
| intergenic    |    -0.36 |       -0.43 |     -0.45 | -0.43 |

In [15]:
datas

shape: (25_019_780, 11)
┌────────────┬───────────┬─────────────┬────────────┬───┬─────┬───────┬───────────┬────────┐
│ chromosome ┆ position  ┆ context     ┆ type       ┆ … ┆ 3N  ┆ 5N    ┆ db        ┆ impact │
│ ---        ┆ ---       ┆ ---         ┆ ---        ┆   ┆ --- ┆ ---   ┆ ---       ┆ ---    │
│ str        ┆ i64       ┆ str         ┆ str        ┆   ┆ str ┆ str   ┆ str       ┆ str    │
╞════════════╪═══════════╪═════════════╪════════════╪═══╪═════╪═══════╪═══════════╪════════╡
│ chr6       ┆ 110621261 ┆ GGTCCCGTTGG ┆ missense   ┆ … ┆ CCG ┆ CCCGT ┆ cosmic    ┆ null   │
│ chr14      ┆ 77277249  ┆ TGGGTCCTGGT ┆ UTR        ┆ … ┆ TCC ┆ GTCCT ┆ cosmic    ┆ null   │
│ chrX       ┆ 72591570  ┆ AAAAAGAAAAA ┆ intronic   ┆ … ┆ AGA ┆ AAGAA ┆ cosmic    ┆ null   │
│ chr10      ┆ 104897737 ┆ GAATATAGTCT ┆ intronic   ┆ … ┆ ATA ┆ TATAG ┆ cosmic    ┆ null   │
│ chr13      ┆ 102846322 ┆ AGCCCCGAAGC ┆ silent     ┆ … ┆ CCG ┆ CCCGA ┆ cosmic    ┆ null   │
│ …          ┆ …         ┆ …           ┆ …          ┆ … ┆ …   ┆ …     ┆ …         ┆ …      │
│ chr1       ┆ 112654988 ┆ TTAACCTTTTA ┆ intronic   ┆ … ┆ CCT ┆ ACCTT ┆ somamutdb ┆ null   │
│ chr5       ┆ 4910326   ┆ TCCCTTCCACA ┆ intergenic ┆ … ┆ TTC ┆ CTTCC ┆ somamutdb ┆ null   │
│ chr4       ┆ 142619007 ┆ ATCACCAGGTA ┆ intronic   ┆ … ┆ CCA ┆ ACCAG ┆ somamutdb ┆ null   │
│ chr1       ┆ 46868237  ┆ AAATTCAAAAT ┆ intergenic ┆ … ┆ TCA ┆ TTCAA ┆ somamutdb ┆ null   │
│ chr4       ┆ 147346286 ┆ GTCTAATCTAT ┆ intergenic ┆ … ┆ AAT ┆ TAATC ┆ somamutdb ┆ null   │
└────────────┴───────────┴─────────────┴────────────┴───┴─────┴───────┴───────────┴────────┘

# Global correlation
## Triplicate

In [54]:
a = datas.with_columns(pl.lit('all').alias('db'), pl.lit('all').alias('type'))

aggregated = utils.aggregate_data(
    datas.with_columns(pl.lit('all').alias('db'), pl.lit('all').alias('type')).group_by(["3N", "type", "db"]).len(),
    kmer3,
    on=["db", "type", "context"],
    over=["db", "type"],
    context_col="3N",
)
print(stats.pearsonr(aggregated['vip'], aggregated["F"]))
compute_partial_corr_table(aggregated, type_order=["all"], db_order=["all"])

PearsonRResult(statistic=np.float64(-0.7541211982350334), pvalue=np.float64(6.226629157978895e-07))

shape: (1, 2)
┌──────┬───────────┐
│ type ┆ all       │
│ ---  ┆ ---       │
│ str  ┆ f64       │
╞══════╪═══════════╡
│ all  ┆ -0.576404 │
└──────┴───────────┘

## Quintuplet

In [58]:
aggregated = utils.aggregate_data(
    filtered_df.with_columns(pl.lit('all').alias('db'), pl.lit('all').alias('type')).group_by(["5N", "type", "db"]).len(),
    kmer5,
    on=["db",  "type", "context"],
    over=["db", "type"],
    context_col="5N",
)
print(stats.pearsonr(aggregated['vip'], aggregated["F"]))
compute_partial_corr_table(aggregated, type_order=["all"], db_order=["all"])

PearsonRResult(statistic=np.float64(-0.7121653638580533), pvalue=np.float64(2.1388223905018615e-80))

shape: (1, 2)
┌──────┬───────────┐
│ type ┆ all       │
│ ---  ┆ ---       │
│ str  ┆ f64       │
╞══════╪═══════════╡
│ all  ┆ -0.567056 │
└──────┴───────────┘